//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCIMIGRATION.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CCIMIGRATION.Resources.Localization.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account will be verfied.
        /// </summary>
        public static string Account_verfied_Admin {
            get {
                return ResourceManager.GetString("Account_verfied_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter or select the alert message.
        /// </summary>
        public static string AddEvacutationMessage {
            get {
                return ResourceManager.GetString("AddEvacutationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Visitor.
        /// </summary>
        public static string AddNewVisitor {
            get {
                return ResourceManager.GetString("AddNewVisitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert Message.
        /// </summary>
        public static string AlertMessage {
            get {
                return ResourceManager.GetString("AlertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerts.
        /// </summary>
        public static string Alerts {
            get {
                return ResourceManager.GetString("Alerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow in settings.
        /// </summary>
        public static string AllowInSettings {
            get {
                return ResourceManager.GetString("AllowInSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This request is already approved.
        /// </summary>
        public static string AlreadyApproved {
            get {
                return ResourceManager.GetString("AlreadyApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already checked in.
        /// </summary>
        public static string AlreadyCheckedIn {
            get {
                return ResourceManager.GetString("AlreadyCheckedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already checked out.
        /// </summary>
        public static string AlreadyCheckedOut {
            get {
                return ResourceManager.GetString("AlreadyCheckedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply For Leave.
        /// </summary>
        public static string ApplyForHoliday {
            get {
                return ResourceManager.GetString("ApplyForHoliday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply For Holiday.
        /// </summary>
        public static string ApplyHolidayText {
            get {
                return ResourceManager.GetString("ApplyHolidayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPTRAX.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        public static string April {
            get {
                return ResourceManager.GetString("April", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance.
        /// </summary>
        public static string Attendance {
            get {
                return ResourceManager.GetString("Attendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        public static string August {
            get {
                return ResourceManager.GetString("August", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticate access to login to app.
        /// </summary>
        public static string Authenticateaccesstologintoapp {
            get {
                return ResourceManager.GetString("Authenticateaccesstologintoapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticating.
        /// </summary>
        public static string Authenticating {
            get {
                return ResourceManager.GetString("Authenticating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        public static string Authentication {
            get {
                return ResourceManager.GetString("Authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorized by.
        /// </summary>
        public static string AuthorizedBy {
            get {
                return ResourceManager.GetString("AuthorizedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calender.
        /// </summary>
        public static string Calender {
            get {
                return ResourceManager.GetString("Calender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera unavailable.
        /// </summary>
        public static string CameraUnavailable {
            get {
                return ResourceManager.GetString("CameraUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must have worked on atleast any one site to apply holiday.
        /// </summary>
        public static string CannotApplyHoliday {
            get {
                return ResourceManager.GetString("CannotApplyHoliday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must have worked on atleast any one site to see employees.
        /// </summary>
        public static string CannotSeeEmployees {
            get {
                return ResourceManager.GetString("CannotSeeEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must have worked on atleast any one site to check holiday.
        /// </summary>
        public static string CannotSeeHoliday {
            get {
                return ResourceManager.GetString("CannotSeeHoliday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture.
        /// </summary>
        public static string Capture {
            get {
                return ResourceManager.GetString("Capture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captured.
        /// </summary>
        public static string Captured {
            get {
                return ResourceManager.GetString("Captured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capturing....
        /// </summary>
        public static string Capturing {
            get {
                return ResourceManager.GetString("Capturing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        public static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your mail to reset password.
        /// </summary>
        public static string CheckEmailForResetPassword {
            get {
                return ResourceManager.GetString("CheckEmailForResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check In.
        /// </summary>
        public static string CheckIn {
            get {
                return ResourceManager.GetString("CheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-In.
        /// </summary>
        public static string CheckInButtonText {
            get {
                return ResourceManager.GetString("CheckInButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckOut.
        /// </summary>
        public static string CheckOut {
            get {
                return ResourceManager.GetString("CheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-Out.
        /// </summary>
        public static string CheckoutButtonText {
            get {
                return ResourceManager.GetString("CheckoutButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must checkout first.
        /// </summary>
        public static string CheckOutValidation {
            get {
                return ResourceManager.GetString("CheckOutValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to start.
        /// </summary>
        public static string ClickToStart {
            get {
                return ResourceManager.GetString("ClickToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock In.
        /// </summary>
        public static string ClockIn {
            get {
                return ResourceManager.GetString("ClockIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock Out.
        /// </summary>
        public static string ClockOut {
            get {
                return ResourceManager.GetString("ClockOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the code.
        /// </summary>
        public static string CodeValidation {
            get {
                return ResourceManager.GetString("CodeValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming Soon.
        /// </summary>
        public static string ComingSoon {
            get {
                return ResourceManager.GetString("ComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Pin.
        /// </summary>
        public static string ConfirmPasswordPlaceholder {
            get {
                return ResourceManager.GetString("ConfirmPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and confirm password not matched.
        /// </summary>
        public static string ConfirmPasswordValidation {
            get {
                return ResourceManager.GetString("ConfirmPasswordValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm pin doesnot match with Pin.
        /// </summary>
        public static string ConfirmPinValidation {
            get {
                return ResourceManager.GetString("ConfirmPinValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Contractor.
        /// </summary>
        public static string Contractor {
            get {
                return ResourceManager.GetString("Contractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select a Contractor.
        /// </summary>
        public static string ContractorValidation {
            get {
                return ResourceManager.GetString("ContractorValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please create a pin.
        /// </summary>
        public static string CreatePinTitle {
            get {
                return ResourceManager.GetString("CreatePinTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting your current site.
        /// </summary>
        public static string CurrentSiteError {
            get {
                return ResourceManager.GetString("CurrentSiteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        public static string December {
            get {
                return ResourceManager.GetString("December", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOB.
        /// </summary>
        public static string DOBPlaceholder {
            get {
                return ResourceManager.GetString("DOBPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid DOB.
        /// </summary>
        public static string DOBValidation {
            get {
                return ResourceManager.GetString("DOBValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        public static string DontHaveAccount {
            get {
                return ResourceManager.GetString("DontHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Email.
        /// </summary>
        public static string EmailPlaceHolder {
            get {
                return ResourceManager.GetString("EmailPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid email.
        /// </summary>
        public static string EmailValidation {
            get {
                return ResourceManager.GetString("EmailValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter employee id.
        /// </summary>
        public static string EmpIdValidation {
            get {
                return ResourceManager.GetString("EmpIdValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Employer.
        /// </summary>
        public static string Employer {
            get {
                return ResourceManager.GetString("Employer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select an Employer.
        /// </summary>
        public static string EmployerValidation {
            get {
                return ResourceManager.GetString("EmployerValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Employee Id.
        /// </summary>
        public static string EmpPlaceholder {
            get {
                return ResourceManager.GetString("EmpPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Location.
        /// </summary>
        public static string EnableLocation {
            get {
                return ResourceManager.GetString("EnableLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enable device location and give access to the app.
        /// </summary>
        public static string EnableLocationAndAccess {
            get {
                return ResourceManager.GetString("EnableLocationAndAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enable location settings to check in.
        /// </summary>
        public static string EnableLocationForCheckIn {
            get {
                return ResourceManager.GetString("EnableLocationForCheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End:.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Holiday.
        /// </summary>
        public static string EndHoliday {
            get {
                return ResourceManager.GetString("EndHoliday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time.
        /// </summary>
        public static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error capturing photo.
        /// </summary>
        public static string ErrorCapturingPhoto {
            get {
                return ResourceManager.GetString("ErrorCapturingPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error compressing photos.
        /// </summary>
        public static string ErrorCompressing {
            get {
                return ResourceManager.GetString("ErrorCompressing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting your location.
        /// </summary>
        public static string ErrorGettingLocation {
            get {
                return ResourceManager.GetString("ErrorGettingLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting monitoring time. You will be monitored every one minute.
        /// </summary>
        public static string ErrorGettingTime {
            get {
                return ResourceManager.GetString("ErrorGettingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in adding face to azure.
        /// </summary>
        public static string ErrorUploadingAzure {
            get {
                return ResourceManager.GetString("ErrorUploadingAzure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in uploading images to server.
        /// </summary>
        public static string ErrorUploadingImage {
            get {
                return ResourceManager.GetString("ErrorUploadingImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent.
        /// </summary>
        public static string EvacuationAlertSuccess {
            get {
                return ResourceManager.GetString("EvacuationAlertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please look into the camera.
        /// </summary>
        public static string FaceCaptureTitle {
            get {
                return ResourceManager.GetString("FaceCaptureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face Not Matched. Please try again.
        /// </summary>
        public static string FaceNotMatch {
            get {
                return ResourceManager.GetString("FaceNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to sign in.
        /// </summary>
        public static string FailedCheckIn {
            get {
                return ResourceManager.GetString("FailedCheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to sign out.
        /// </summary>
        public static string FailedCheckOut {
            get {
                return ResourceManager.GetString("FailedCheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February.
        /// </summary>
        public static string February {
            get {
                return ResourceManager.GetString("February", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failed. Please try again.
        /// </summary>
        public static string FingerAuthFailedMessage {
            get {
                return ResourceManager.GetString("FingerAuthFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstNamePlaceholder {
            get {
                return ResourceManager.GetString("FirstNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid first name.
        /// </summary>
        public static string FNameValidation {
            get {
                return ResourceManager.GetString("FNameValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter 4 digit pin.
        /// </summary>
        public static string FourDigitPin {
            get {
                return ResourceManager.GetString("FourDigitPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started.
        /// </summary>
        public static string GetStarted {
            get {
                return ResourceManager.GetString("GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Back.
        /// </summary>
        public static string GoBack {
            get {
                return ResourceManager.GetString("GoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please go back to the site, otherwise you will be logged out.
        /// </summary>
        public static string GoBackLocationWarning {
            get {
                return ResourceManager.GetString("GoBackLocationWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please grant camera permission.
        /// </summary>
        public static string GrantCameraPermission {
            get {
                return ResourceManager.GetString("GrantCameraPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have a safe day.
        /// </summary>
        public static string HaveSafeDay {
            get {
                return ResourceManager.GetString("HaveSafeDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holiday.
        /// </summary>
        public static string Holiday {
            get {
                return ResourceManager.GetString("Holiday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request approved successfully.
        /// </summary>
        public static string HolidayApprovedSuccess {
            get {
                return ResourceManager.GetString("HolidayApprovedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holiday Calender.
        /// </summary>
        public static string HolidayCalender {
            get {
                return ResourceManager.GetString("HolidayCalender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date/time must be less then end date/time.
        /// </summary>
        public static string HolidayDateTimeValidatonError {
            get {
                return ResourceManager.GetString("HolidayDateTimeValidatonError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request declined successfully.
        /// </summary>
        public static string HolidayRejectSuccess {
            get {
                return ResourceManager.GetString("HolidayRejectSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your holiday request ​has been submitted.
        /// </summary>
        public static string HolidayRequestSubimtted {
            get {
                return ResourceManager.GetString("HolidayRequestSubimtted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can confirm i have all the safety equipements to carry out my job.
        /// </summary>
        public static string IConfirmSafetyMeasures {
            get {
                return ResourceManager.GetString("IConfirmSafetyMeasures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your images has been deleted by admin. Please recapture..
        /// </summary>
        public static string ImageDeleteMessage {
            get {
                return ResourceManager.GetString("ImageDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gray.
        /// </summary>
        public static string InputFieldPlaceholderColor {
            get {
                return ResourceManager.GetString("InputFieldPlaceholderColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide the valid input to the fields.
        /// </summary>
        public static string InputFieldValidationError {
            get {
                return ResourceManager.GetString("InputFieldValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter insurance number.
        /// </summary>
        public static string InsuranceNumberValidation {
            get {
                return ResourceManager.GetString("InsuranceNumberValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is on leave on.
        /// </summary>
        public static string Isonleaveon {
            get {
                return ResourceManager.GetString("Isonleaveon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January.
        /// </summary>
        public static string January {
            get {
                return ResourceManager.GetString("January", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        public static string July {
            get {
                return ResourceManager.GetString("July", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        public static string June {
            get {
                return ResourceManager.GetString("June", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastNamePlaceholder {
            get {
                return ResourceManager.GetString("LastNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorized.
        /// </summary>
        public static string LeaveStatusApproved {
            get {
                return ResourceManager.GetString("LeaveStatusApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applied.
        /// </summary>
        public static string LeaveStatusPending {
            get {
                return ResourceManager.GetString("LeaveStatusPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not-Authorized.
        /// </summary>
        public static string LeaveStatusRejected {
            get {
                return ResourceManager.GetString("LeaveStatusRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LightGray.
        /// </summary>
        public static string LightGray {
            get {
                return ResourceManager.GetString("LightGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid last name.
        /// </summary>
        public static string LNameValidation {
            get {
                return ResourceManager.GetString("LNameValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading...
        /// </summary>
        public static string Loading1 {
            get {
                return ResourceManager.GetString("Loading1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading sites.
        /// </summary>
        public static string LoadingSites {
            get {
                return ResourceManager.GetString("LoadingSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading TimeSheet.
        /// </summary>
        public static string LoadingTimeSheet {
            get {
                return ResourceManager.GetString("LoadingTimeSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app collects location data to enable Geofence which will track the movement of a user while working on a site even when the application is closed or not in use. After that only, Users will be able to sign in and can mark their attendance. It helps an organization to track their employees on the site and keep a track of attendance. Please grant &quot;Always allow&quot; permission..
        /// </summary>
        public static string LocationConsent {
            get {
                return ResourceManager.GetString("LocationConsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please turn on the location, otherwise you will be signed out.
        /// </summary>
        public static string LocationOnWarning {
            get {
                return ResourceManager.GetString("LocationOnWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loction Required.
        /// </summary>
        public static string LocationRequired {
            get {
                return ResourceManager.GetString("LocationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location unavailable.
        /// </summary>
        public static string LocationUnavailable {
            get {
                return ResourceManager.GetString("LocationUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging Out....
        /// </summary>
        public static string Logging_Out {
            get {
                return ResourceManager.GetString("Logging Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging in.
        /// </summary>
        public static string LogginIn {
            get {
                return ResourceManager.GetString("LogginIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginButtonText {
            get {
                return ResourceManager.GetString("LoginButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with pin or device biometrics.
        /// </summary>
        public static string LoginWithFingerOrPin {
            get {
                return ResourceManager.GetString("LoginWithFingerOrPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please look into the camera and move your head from left to right..
        /// </summary>
        public static string LookintoCamera {
            get {
                return ResourceManager.GetString("LookintoCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mothers Maiden Name.
        /// </summary>
        public static string MaidenPlaceHolder {
            get {
                return ResourceManager.GetString("MaidenPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure your device location is turned on.
        /// </summary>
        public static string MakeSureLocationOn {
            get {
                return ResourceManager.GetString("MakeSureLocationOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        public static string March {
            get {
                return ResourceManager.GetString("March", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        public static string May {
            get {
                return ResourceManager.GetString("May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calender.
        /// </summary>
        public static string MenuCalender {
            get {
                return ResourceManager.GetString("MenuCalender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evacuation.
        /// </summary>
        public static string MenuEvacuation {
            get {
                return ResourceManager.GetString("MenuEvacuation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holiday.
        /// </summary>
        public static string MenuHoliday {
            get {
                return ResourceManager.GetString("MenuHoliday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string MenuHome {
            get {
                return ResourceManager.GetString("MenuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string MenuLogout {
            get {
                return ResourceManager.GetString("MenuLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timesheet.
        /// </summary>
        public static string MenuTimesheet {
            get {
                return ResourceManager.GetString("MenuTimesheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitors.
        /// </summary>
        public static string MenuVisitors {
            get {
                return ResourceManager.GetString("MenuVisitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Mobile Number.
        /// </summary>
        public static string MobilePlaceHolder {
            get {
                return ResourceManager.GetString("MobilePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mothers Maiden Name required for security question.
        /// </summary>
        public static string MotherNameRequired {
            get {
                return ResourceManager.GetString("MotherNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter mothers maiden name.
        /// </summary>
        public static string MotherNameValidation {
            get {
                return ResourceManager.GetString("MotherNameValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Name.
        /// </summary>
        public static string NamePlaceHolder {
            get {
                return ResourceManager.GetString("NamePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter name.
        /// </summary>
        public static string NameValidation {
            get {
                return ResourceManager.GetString("NameValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optrax need your location in background. Please allow locatio permission to always.
        /// </summary>
        public static string NeedLocationInBackgrund {
            get {
                return ResourceManager.GetString("NeedLocationInBackgrund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Insurance Id.
        /// </summary>
        public static string NIdPlaceholder {
            get {
                return ResourceManager.GetString("NIdPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NI Number.
        /// </summary>
        public static string NINumberPlaceholder {
            get {
                return ResourceManager.GetString("NINumberPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid NI Number.
        /// </summary>
        public static string NIValidation {
            get {
                return ResourceManager.GetString("NIValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data.
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO EVENTS FOR THE SELECTED DATE.
        /// </summary>
        public static string NoEvents {
            get {
                return ResourceManager.GetString("NoEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No holiday events found.
        /// </summary>
        public static string NoHolidayEventFound {
            get {
                return ResourceManager.GetString("NoHolidayEventFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All input fields should be filled.
        /// </summary>
        public static string NoInputError {
            get {
                return ResourceManager.GetString("NoInputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Check your internet connection.
        /// </summary>
        public static string NoInternet {
            get {
                return ResourceManager.GetString("NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Non Auth).
        /// </summary>
        public static string NonAuth {
            get {
                return ResourceManager.GetString("NonAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not allowed to work on site untill correct PPE has been obtained.
        /// </summary>
        public static string NotAllowedToWorkonSite {
            get {
                return ResourceManager.GetString("NotAllowedToWorkonSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not in site reach.
        /// </summary>
        public static string NotInSiteReach {
            get {
                return ResourceManager.GetString("NotInSiteReach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not on an active ECL Site.
        /// </summary>
        public static string NotOnActiveSite {
            get {
                return ResourceManager.GetString("NotOnActiveSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not any site.
        /// </summary>
        public static string NotOnSite {
            get {
                return ResourceManager.GetString("NotOnSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        public static string November {
            get {
                return ResourceManager.GetString("November", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to October.
        /// </summary>
        public static string October {
            get {
                return ResourceManager.GetString("October", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline data sync error.
        /// </summary>
        public static string OfflineSyncError {
            get {
                return ResourceManager.GetString("OfflineSyncError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are on an active ECL Site.
        /// </summary>
        public static string OnActiveSite {
            get {
                return ResourceManager.GetString("OnActiveSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Settings to enable location.
        /// </summary>
        public static string OpenSettingsForLocation {
            get {
                return ResourceManager.GetString("OpenSettingsForLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Contractor.
        /// </summary>
        public static string OtherContractor {
            get {
                return ResourceManager.GetString("OtherContractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Trade.
        /// </summary>
        public static string OtherTradePlaceholder {
            get {
                return ResourceManager.GetString("OtherTradePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of site.
        /// </summary>
        public static string OutOfSite {
            get {
                return ResourceManager.GetString("OutOfSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evacuation.
        /// </summary>
        public static string PageTitleEvacuation {
            get {
                return ResourceManager.GetString("PageTitleEvacuation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holiday Requests.
        /// </summary>
        public static string PageTitleHoliday {
            get {
                return ResourceManager.GetString("PageTitleHoliday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitors.
        /// </summary>
        public static string PageTitleVisitors {
            get {
                return ResourceManager.GetString("PageTitleVisitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password does not match.
        /// </summary>
        public static string PasswordNotMatch {
            get {
                return ResourceManager.GetString("PasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Pin.
        /// </summary>
        public static string PasswordPlaceholder {
            get {
                return ResourceManager.GetString("PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset success. Please login.
        /// </summary>
        public static string PasswordResetSuccess {
            get {
                return ResourceManager.GetString("PasswordResetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid password.
        /// </summary>
        public static string PasswordValidation {
            get {
                return ResourceManager.GetString("PasswordValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please grant location permission.
        /// </summary>
        public static string PermissionError {
            get {
                return ResourceManager.GetString("PermissionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid phone number of 11 digits.
        /// </summary>
        public static string PhoneNumberError {
            get {
                return ResourceManager.GetString("PhoneNumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Phone.
        /// </summary>
        public static string PhoneNumberPlaceholder {
            get {
                return ResourceManager.GetString("PhoneNumberPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid phone number .
        /// </summary>
        public static string PhoneValidation {
            get {
                return ResourceManager.GetString("PhoneValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your images has been re-captured successfully. You need to contact your administration to activate your account..
        /// </summary>
        public static string PhotoRecapturedContactAdmin {
            get {
                return ResourceManager.GetString("PhotoRecapturedContactAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You photos have been submitted, please contact admin to approve and login.
        /// </summary>
        public static string PhotosSubmitted {
            get {
                return ResourceManager.GetString("PhotosSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin.
        /// </summary>
        public static string Pin {
            get {
                return ResourceManager.GetString("Pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Pin.
        /// </summary>
        public static string PinPlaceholder {
            get {
                return ResourceManager.GetString("PinPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the 4 digit pin.
        /// </summary>
        public static string PinValidation {
            get {
                return ResourceManager.GetString("PinValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place your finger on scanner to login.
        /// </summary>
        public static string Placefinger {
            get {
                return ResourceManager.GetString("Placefinger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Here.
        /// </summary>
        public static string PressHere {
            get {
                return ResourceManager.GetString("PressHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed.
        /// </summary>
        public static string Proceed {
            get {
                return ResourceManager.GetString("Proceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Capture.
        /// </summary>
        public static string ReCapture {
            get {
                return ResourceManager.GetString("ReCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received.
        /// </summary>
        public static string Received {
            get {
                return ResourceManager.GetString("Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Registration.
        /// </summary>
        public static string RegisterFormTitle {
            get {
                return ResourceManager.GetString("RegisterFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering.
        /// </summary>
        public static string Registering {
            get {
                return ResourceManager.GetString("Registering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Holiday.
        /// </summary>
        public static string RequestHoliday {
            get {
                return ResourceManager.GetString("RequestHoliday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need to capture photo to check out.
        /// </summary>
        public static string RequiredPhotoForCheckout {
            get {
                return ResourceManager.GetString("RequiredPhotoForCheckout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string ResetCode {
            get {
                return ResourceManager.GetString("ResetCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to login.
        /// </summary>
        public static string ReturnToLogin {
            get {
                return ResourceManager.GetString("ReturnToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please review and confirm you have the following:.
        /// </summary>
        public static string ReviewAndConfirm {
            get {
                return ResourceManager.GetString("ReviewAndConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the safety measures and confirm.
        /// </summary>
        public static string SafetyMesaureErrorMessage {
            get {
                return ResourceManager.GetString("SafetyMesaureErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving Pin.
        /// </summary>
        public static string SavingPin {
            get {
                return ResourceManager.GetString("SavingPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search contractor.
        /// </summary>
        public static string SearchContractor {
            get {
                return ResourceManager.GetString("SearchContractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search employer.
        /// </summary>
        public static string SearchEmployer {
            get {
                return ResourceManager.GetString("SearchEmployer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search trade.
        /// </summary>
        public static string SearchTrade {
            get {
                return ResourceManager.GetString("SearchTrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select contractor.
        /// </summary>
        public static string SelectContractorError {
            get {
                return ResourceManager.GetString("SelectContractorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select employer.
        /// </summary>
        public static string SelectEmployerError {
            get {
                return ResourceManager.GetString("SelectEmployerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        public static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the other contractor.
        /// </summary>
        public static string SelectOtherOntractorError {
            get {
                return ResourceManager.GetString("SelectOtherOntractorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the other trade.
        /// </summary>
        public static string SelectOtherTradeError {
            get {
                return ResourceManager.GetString("SelectOtherTradeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Site.
        /// </summary>
        public static string SelectSite {
            get {
                return ResourceManager.GetString("SelectSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select trade.
        /// </summary>
        public static string SelectTradeError {
            get {
                return ResourceManager.GetString("SelectTradeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select users to send alert.
        /// </summary>
        public static string SelectUserForEvacuation {
            get {
                return ResourceManager.GetString("SelectUserForEvacuation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Alert.
        /// </summary>
        public static string SendAlert {
            get {
                return ResourceManager.GetString("SendAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent.
        /// </summary>
        public static string Sent {
            get {
                return ResourceManager.GetString("Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        public static string September {
            get {
                return ResourceManager.GetString("September", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Time.
        /// </summary>
        public static string ShiftTime {
            get {
                return ResourceManager.GetString("ShiftTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site &amp; Date.
        /// </summary>
        public static string SiteAndDate {
            get {
                return ResourceManager.GetString("SiteAndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select site first.
        /// </summary>
        public static string SiteValidation {
            get {
                return ResourceManager.GetString("SiteValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong.
        /// </summary>
        public static string SomethingwentWrong {
            get {
                return ResourceManager.GetString("SomethingwentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. please try again.
        /// </summary>
        public static string SomethingWentWrongTryAgain {
            get {
                return ResourceManager.GetString("SomethingWentWrongTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff on.
        /// </summary>
        public static string Staffon {
            get {
                return ResourceManager.GetString("Staffon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff On Site.
        /// </summary>
        public static string StaffOnSite {
            get {
                return ResourceManager.GetString("StaffOnSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start:.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Holiday.
        /// </summary>
        public static string StartHoliday {
            get {
                return ResourceManager.GetString("StartHoliday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit for Approvel.
        /// </summary>
        public static string SubmitApprovel {
            get {
                return ResourceManager.GetString("SubmitApprovel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncing time.
        /// </summary>
        public static string SyncingTime {
            get {
                return ResourceManager.GetString("SyncingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank You for Registering.
        /// </summary>
        public static string ThankYou_for_Registering {
            get {
                return ResourceManager.GetString("ThankYou_for_Registering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this week.
        /// </summary>
        public static string ThisWeek {
            get {
                return ResourceManager.GetString("ThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timesheets.
        /// </summary>
        public static string TimeSheets {
            get {
                return ResourceManager.GetString("TimeSheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time synced.
        /// </summary>
        public static string TimeSynced {
            get {
                return ResourceManager.GetString("TimeSynced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade.
        /// </summary>
        public static string Trade {
            get {
                return ResourceManager.GetString("Trade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select a Trade.
        /// </summary>
        public static string TradeValidation {
            get {
                return ResourceManager.GetString("TradeValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn on.
        /// </summary>
        public static string TurnOn {
            get {
                return ResourceManager.GetString("TurnOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Registration.
        /// </summary>
        public static string UserRegistration {
            get {
                return ResourceManager.GetString("UserRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Hours.
        /// </summary>
        public static string WorkingHours {
            get {
                return ResourceManager.GetString("WorkingHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already signed in, please sign out last session.
        /// </summary>
        public static string YouAreAlreadyCheckedIn {
            get {
                return ResourceManager.GetString("YouAreAlreadyCheckedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are in.
        /// </summary>
        public static string YouAreIn {
            get {
                return ResourceManager.GetString("YouAreIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are signed out.
        /// </summary>
        public static string YouAreSignedOut {
            get {
                return ResourceManager.GetString("YouAreSignedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can now work on.
        /// </summary>
        public static string YouCanWorkOn {
            get {
                return ResourceManager.GetString("YouCanWorkOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have worked .
        /// </summary>
        public static string YouHaveWorked {
            get {
                return ResourceManager.GetString("YouHaveWorked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must first checkin to see the holiday requests.
        /// </summary>
        public static string YouMustCheckInForHoliday {
            get {
                return ResourceManager.GetString("YouMustCheckInForHoliday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must sign out first.
        /// </summary>
        public static string YouMustCheckOutFirst {
            get {
                return ResourceManager.GetString("YouMustCheckOutFirst", resourceCulture);
            }
        }
    }
}
